MVCSmartHouse/Controllers/SmartHouseController.cs
using MVCSmartHouse.ViewModels.AdaptInterfacies;
using MVCSmartHouse.ViewModels.AdaptModels;
using SimpleSmartHouse1._0;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSmartHouse.Controllers
{
    public class SmartHouseController : Controller
    {
        IVolumeAble vol;
        IChannelAble ch;
        ISetChannelAble chList;
        ITemperatureAble temperat;

        public ActionResult Index()
        {
            IDictionary<int, Device> deviceDictionary;

            if (Session["Device"] == null)
            {
                deviceDictionary = new SortedDictionary<int, Device>();
                deviceDictionary.Add(1, new NewTV("TV", false, new Parametr(1, 50, 3), new Parametr(1, 45, 12), new ChangeSetting(), BrightnessLevel.Default, new ListFunction()));
                deviceDictionary.Add(2, new NewRadio("Radio", false, new Parametr(1, 13, 3), new Parametr(1, 45, 10), new ChangeSetting(), new ListFunction()));
                deviceDictionary.Add(3, new NewHeater("Heater", false, Mode.Eco, new Parametr(15, 34, 18), new ChangeSetting()));
                deviceDictionary.Add(4, new NewAirCondition("AirCondition", false, Mode.Low, new Parametr(8, 26, 18), new ChangeSetting()));
                deviceDictionary.Add(5, new NewIlluminator("Illuminator", false, IlluminatorBrightness.Default));
                Session["Device"] = deviceDictionary;
                Session["NextId"] = 6;
            }
            else
            {
                deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            }
            SelectListItem[] deviceList = new SelectListItem[5];
            deviceList[0] = new SelectListItem { Text = "TV", Value = "TV", Selected = true };
            deviceList[1] = new SelectListItem { Text = "Radio", Value = "Radio" };
            deviceList[2] = new SelectListItem { Text = "Heater", Value = "Heater" };
            deviceList[3] = new SelectListItem { Text = "AirCodition", Value = "AirCodition" };
            deviceList[4] = new SelectListItem { Text = "Illuminator", Value = "Illuminator" };
            ViewBag.DeviceList = deviceList;
            return View(deviceDictionary);
        }

        //ADD
        public ActionResult Add(string device)
        {
            Device newDevice;
            switch (device)
            {
                default:
                    newDevice = new NewTV("TV", false, new Parametr(1, 50, 3), new Parametr(1, 45, 15), new ChangeSetting(), BrightnessLevel.Default, new ListFunction());
                    break;
                case "Radio":
                    newDevice = new NewRadio("Radio", false, new Parametr(1, 13, 3), new Parametr(1, 45, 15), new ChangeSetting(), new ListFunction());
                    break;
                case "Heater":
                    newDevice = new NewHeater("Heater", false, Mode.Eco, new Parametr(8, 15, 12), new ChangeSetting());
                    break;
                case "AirCondition":
                    newDevice = new NewAirCondition("AirCondition", false, Mode.Low, new Parametr(8, 15, 12), new ChangeSetting());
                    break;
                case "Illuminator":
                    newDevice = new NewIlluminator("Illuminator", false, IlluminatorBrightness.Default);
                    break;
            }
            int id = (int)Session["NextId"];
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            deviceDictionary.Add(id, newDevice);
            id++;
            Session["NextId"] = id;
            return RedirectToAction("Index");
        }

        public ActionResult MainFunc(int id, string command)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            if (deviceDictionary[id] is Device)
            {
                if (deviceDictionary[id] is IVolumeAble)
                {
                    vol = (IVolumeAble)deviceDictionary[id];//inc decr VOLUME
                }
                if (deviceDictionary[id] is IChannelAble)
                {
                    ch = (IChannelAble)deviceDictionary[id];//inc decr CHANNEL
                }
                if (deviceDictionary[id] is ISetChannelAble)
                {
                    chList = (ISetChannelAble)deviceDictionary[id];//Load Show  CHAN_LIst  HIDE_LIst 
                }
                if (deviceDictionary[id] is ITemperatureAble)
                {
                    temperat = (ITemperatureAble)deviceDictionary[id];// inc decr TEMPERATURE
                }

                switch (command)
                {
                    case "On":
                        deviceDictionary[id].SwtchOn();
                        break;
                    case "Off":
                        deviceDictionary[id].SwtchOff();
                        break;
                    case "Del":
                        deviceDictionary.Remove(id);
                        break;
                    case "IncVol":
                        vol.IncreaseVolume();
                        break;
                    case "DecVol":
                        vol.DecreaseVolume();
                        break;
                    case "IncCh":
                        ch.IncreaseChannel();
                        break;
                    case "DecCh":
                        ch.DecreaseChannel();
                        break;
                    case "LoadChan":
                        chList.LoadChannel();
                        break;
                    case "ShowChan":
                        if (deviceDictionary[id].State)
                        {
                            if (deviceDictionary[id] is NewTV)
                            {
                                Session["TVList"] = chList.ShowChannelList();
                            }
                            if (deviceDictionary[id] is NewRadio)
                            {
                                Session["RadioList"] = chList.ShowChannelList();
                            }
                        }
                        break;
                    case "HideChan":
                        if (chList is NewTV)
                        {
                            Session["TVList"] = null;
                        }
                        if (chList is NewRadio)
                        {
                            Session["RadioList"] = null;
                        }
                        break;
                    case "IncTemp":
                        temperat.IncreaseTemperature();
                        break;
                    case "DecTemp":
                        temperat.DecreaseTemperature();
                        break;
                }
            }
            return RedirectToAction("Index");
        }

        //HandSetTemperatureHeater
        public ActionResult SetHeatTemperature(int id, int warmTemper = 15)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetTempWarmAble)deviceDictionary[id]).HandSetTemperature(warmTemper);
            return RedirectToAction("Index");
        }
        //HandSetTemperatureAC
        public ActionResult SetColdTemperature(int id, int coldTemper = 15)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetTempColdAble)deviceDictionary[id]).HandSetTemperature(coldTemper);
            return RedirectToAction("Index");
        }

        //HandSetVolume
        public ActionResult SetTVVolume(int id, int tvVolume = 8)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetTVVolumeAble)deviceDictionary[id]).HandSetVolume(tvVolume);
            return RedirectToAction("Index");
        }

        public ActionResult SetRadioVolume(int id, int rVolume = 8)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetRadioVolumeAble)deviceDictionary[id]).HandSetVolume(rVolume);
            return RedirectToAction("Index");
        }

        //HandSetChannelForTV
        public ActionResult SetTVChannel(int id, int tvChannel = 8)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetTVChannelAble)deviceDictionary[id]).HandSetChannel(tvChannel);
            return RedirectToAction("Index");
        }

        //HandSetChannelForRadio
        public ActionResult SetRadioChannel(int id, int rChannel = 8)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            ((IHandSetRadioChannelAble)deviceDictionary[id]).HandSetChannel(rChannel);
            return RedirectToAction("Index");
        }

        //SetBrightMode 
        public ActionResult SetBrightMode(int id, string brightMode)
        {
            IDictionary<int, Device> deviceDictionary = (SortedDictionary<int, Device>)Session["Device"];
            IMultimediaBrightAble bMode = (IMultimediaBrightAble)deviceDictionary[id];
            Session["BrightMode"] = brightMode;
            switch (brightMode)
            {
                case "Bright":
                    bMode.SetMaxMode();
                    break;
                case "Medium":
                    bMode.SetMiddleMode();
                    break;
                case "Low":
                    bMode.SetMinMode();
                    break;
                default:
                    bMode.SetAutoMode();
                    break;
            }
            return RedirectToAction("Index");
        }

        //SetBrightMode 

MVCSmartHouse/Views/SmartHouse/Index.cshtml
@using System.Web.Mvc.Html
@using MVCSmartHouse.ViewModels.AdaptInterfacies;
@using SimpleSmartHouse1._0

@model IDictionary<int, Device>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <title>Smart House</title>
</head>
<body>
    @using (Html.BeginForm("Add", "SmartHouse"))
    {
        @Html.DropDownList("device", (IEnumerable<SelectListItem>)ViewBag.DeviceList, new { @class = "dropDownDeviceList" })
        <input type="submit" value="Add" class="button" />
        <br />
        foreach (var item in Model)
        {
            <div class="device-div">
                <div class="conditionRow">
                    Device: @item.Value.Name
                    <br />
                    @item.Value.ToString()
                    <br />
                </div>
                <span>@Html.ActionLink("On", "MainFunc", new { id = item.Key, command = "On" }, new { @class = "button" })</span><!-- ON -->
                <span>@Html.ActionLink("Off", "MainFunc", new { id = item.Key, command = "Off" }, new { @class = "button" })</span><!-- OFF -->
                <span>@Html.ActionLink("Del", "MainFunc", new { id = item.Key, command = "Del" }, new { @class = "button" })</span><!-- DEL -->
                <br />
                @if (item.Value is IHandSetTempWarmAble)//Heater
                    {
                        if (item.Value.State == true)
                        {
                        <img src="~/Content/image/RadiatorOn.png" class="img" alt="Radiator On">
                    }
                    else
                    {
                        <img src="~/Content/image/RadiatorOff.png" class="img" alt="Radiator Off">
                    }
                }

                else if (item.Value is IHandSetTempColdAble)//AC
                {
                    if (item.Value.State == true)
                    {
                        <img src="~/Content/image/onAC.png" class="img" alt="Heater On">
                    }
                    else
                    {
                        <img src="~/Content/image/offAC.png" class="img" alt="Heater Off">
                    }
                }

                else if (item.Value is IlluminatorModeAble)//lamp
                {
                    if (item.Value.State == true)
                    {
                        <img src="~/Content/image/onLamp.png" class="img" alt="Lamp On">
                    }
                    else
                    {
                        <img src="~/Content/image/offLamp.png" class="img" alt="Lamp Off">
                    }
                }

                else if (item.Value is IHandSetRadioChannelAble)//Radio
                {
                    if (item.Value.State == true)
                    {
                        <img src="~/Content/image/RadioOn.png" class="img" alt="Radio On">
                    }
                    else
                    {
                        <img src="~/Content/image/RadioOff.png" class="img" alt="Radio Off">
                    }
                }

                else if (item.Value is IHandSetTVChannelAble)//TV
                {
                    if (item.Value.State == true)
                    {
                        <img src="~/Content/image/TVon.png" class="img" alt="TV On">
                    }
                    else
                    {
                        <img src="~/Content/image/TVoff.png" class="img" alt="TV Off">
                    }
                }
                <br />

                @if (item.Value is IHandSetTempWarmAble)
                {
                    <input type="submit" id="@item.Key" formaction="SetHeatTemperature/@item.Key" class="button" value="Set temperature" />
                    @Html.TextBox("warmTemper", Session["warmTemper"], new { id = "warmTemper" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IHandSetTempColdAble)
                {
                    <input type="submit" id="@item.Key" formaction="SetColdTemperature/@item.Key" class="button" value="Set temperature" />
                    @Html.TextBox("coldTemper", Session["coldTemper"], new { id = "coldTemper" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IIncDecTemperatureAble)
                {
                    @Html.ActionLink("Temp +", "MainFunc", new { id = item.Key, command = "IncTemp" }, new { @class = "button" })
                    @Html.ActionLink("Temp -", "MainFunc", new { id = item.Key, command = "DecTemp" }, new { @class = "button" })
                    <br />
                    <br />
                }


                @if (item.Value is IMultimediaBrightAble)
                {
                    <input type="submit" id="@item.Key" formaction="SetBrightMode/@item.Key" class="button" value="Set bright" />
                    @Html.DropDownList("brightMode", new SelectList(new[] {BrightnessLevel.Bright.ToString(),BrightnessLevel.Medium.ToString(),
                                        BrightnessLevel.Low.ToString(),BrightnessLevel.Default.ToString()}),
                          (string)Session["BrightMode"], new { id = "brightMode" + item.Key, @class = "dropDownDeviceList" })
                    <br />
                }

                @if (item.Value is IHandSetTVVolumeAble)
                {
                    <input type="submit" id="@item.Key" formaction="SetTVVolume/@item.Key" class="button" value="Set Volume" />
                    @Html.TextBox("tvVolume", Session["tvVolume"], new { id = "tvVolume" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IHandSetRadioVolumeAble)
                    {
                    <input type="submit" id="@item.Key" formaction="SetRadioVolume/@item.Key" class="button" value="Set Volume" />
                    @Html.TextBox("rVolume", Session["rVolume"], new { id = "rVolume" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IIncDecVolumeAble)
                    {
                    @Html.ActionLink("Volume +", "MainFunc", new { id = item.Key, command = "IncVol" }, new { @class = "button" })<!-- IncreaseVolume -->
                    @Html.ActionLink("Volume -", "MainFunc", new { id = item.Key, command = "DecVol" }, new { @class = "button" })<!-- DecreaseVolume -->
                    <br />
                    <br />
                }


                @if (item.Value is IHandSetTVChannelAble)
                    {
                    <input type="submit" id="@item.Key" formaction="SetTVChannel/@item.Key" class="button" value="Set Channel" /><!--  -->
                    @Html.TextBox("tvChannel", Session["Channel"], new { id = "tvChannel" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IHandSetRadioChannelAble)
                {
                    <input type="submit" id="@item.Key" formaction="SetRadioChannel/@item.Key" class="button" value="Set Channel" /><!--  -->
                    @Html.TextBox("rChannel", Session["rChannel"], new { id = "rChannel" + item.Key, size = "3" })
                    <br />
                    <br />
                }

                @if (item.Value is IIncDecChannelAble)
                    {
                    @Html.ActionLink("Channel +", "MainFunc", new { id = item.Key, command = "IncCh" }, new { @class = "button" })
                    @Html.ActionLink("Channel -", "MainFunc", new { id = item.Key, command = "DecCh" }, new { @class = "button" })
                    <br />
                    <br />
                }

                @if (item.Value is IShowLoadListAble)
                    {
                    @Html.ActionLink("Load Chann List", "MainFunc", new { id = item.Key, command = "LoadChan" }, new { @class = "button" })
                    <br />
                    <br />
                    @Html.ActionLink("Show Chann list", "MainFunc", new { id = item.Key, command = "ShowChan" }, new { @class = "button" })
                    @Html.ActionLink("Hide Chann list", "MainFunc", new { id = item.Key, command = "HideChan" }, new { @class = "button" })
                    <br />
                    <br />
                    if (item.Value.Name == "TV")
                    {
                        @Html.TextArea("TVlist" + @item.Key, (string)Session["TVList"], new { id = item.Key, @class = "textAreaList" });
                    }
                    if (item.Value.Name == "Radio")
                    {
                        @Html.TextArea("Radiolist" + @item.Key, (string)Session["RadioList"], new { id = item.Key, @class = "textAreaList" });
                    }
                }

                @if (item.Value is IWarmModeAble)
                {
                    @Html.DropDownList("warmMode", new SelectList(new[] { Mode.Turbo.ToString(), Mode.Eco.ToString(), Mode.Low.ToString(), Mode.Auto.ToString() }),
                                                (string)Session["wMode"], new { id = "wMode" + item.Key, @class = "dropDownDeviceList" })
                    <input type="submit" id="@item.Key" formaction="SetWarmMode/@item.Key" class="button" value="Set Warm Mode" />
                }

                @if (item.Value is IColdModeAble)
                {
                    @Html.DropDownList("coldMode", new SelectList(new[] { Mode.Turbo.ToString(), Mode.Eco.ToString(), Mode.Low.ToString(), Mode.Auto.ToString() }),
                                    (string)Session["cMode"], new { id = "cMode" + item.Key, @class = "dropDownDeviceList" })
                    <input type="submit" id="@item.Key" formaction="SetColdMode/@item.Key" class="button" value="Set Cold Mode" />
                }

                @if (item.Value is IlluminatorModeAble)
                {
                    @Html.DropDownList("ill", new SelectList(new[] {IlluminatorBrightness.BrightWhite.ToString(), IlluminatorBrightness.Daylight.ToString(),
                           IlluminatorBrightness.WarmWhite.ToString(),IlluminatorBrightness.Default.ToString()}),
                           (string)Session["illBright"], new { id = "illBright" + item.Key, @class = "dropDownDeviceList" })
                    <input type="submit" id="@item.Key" formaction="SetIlluminatorBright/@item.Key" class="button" value="Set bright" />
                }
            </div>
        }
    }
</body>
</html>